apiVersion: batch/v1
kind: Job
metadata:
  name: aggregator
spec:
  template:
    spec:
      containers:
      - name: aggregator
        image: python:3.10-alpine
        command: ["python3", "-c"]
        args:
          - |
            import os, glob
            from collections import defaultdict
            counts = defaultdict(int)
            for file in glob.glob('mnt/data/output_part_*.txt'):
                with open(file) as f:
                    for line in f:
                        word, cnt = line.strip().split()
                        counts[word] += int(cnt)
            with open('mnt/data/final_count.txt', 'w') as f:
                for word in sorted(counts.keys()):
                    f.write(f'{word} {counts[word]}\\n')
                    print(f'{word} {counts[word]}\\n')
        volumeMounts:
        - name: data
          mountPath: /mnt
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: contapalavras-pvc
      restartPolicy: Never
